Di/views/answer_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from Di import db
from ..forms import AnswerForm
from Di.models import Question, Answer
from .auth_views import login_required

bp = Blueprint('answer', __name__, url_prefix='/answer')

@bp.route('/create/<int:question_id>', methods=('POST',))
@login_required
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        content = request.form['content']
        answer = Answer(content=content, create_date=datetime.now(), user=g.user)
        question.answer_set.append(answer)
        db.session.commit()
        return redirect(url_for('question.detail', question_id=question_id))
    return render_template('question/question_detail.html', question=question, form=form)

@bp.route('/modify/<int:answer_id>', methods=('GET', 'POST'))
@login_required
def modify(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    if g.user != answer.user:
        flash("You don't have permission")
        return redirect(url_for('question.detail', question_id=answer.question.id))
    if request.method == "POST":
        form = AnswerForm()
        if form.validate_on_submit():
            form.populate_obj(answer)
            answer.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect(url_for('question.detail', question_id=answer.question.id))
    else:
        form = AnswerForm(obj=answer)
    return render_template('answer/answer_form.html', form=form)

@bp.route('/delete/<int:answer_id>')
@login_required
def delete(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    question_id = answer.question.id
    if g.user != answer.user:
        flash("You don't have permission")
    else:
        db.session.delete(answer)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

Di/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from Di import db
from Di.forms import UserCreateForm, UserLoginForm
from Di.models import User

import functools

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.password1.data))
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.mainpage'))
        else:
            flash('You already signed.')
    return render_template('auth/signup.html', form=form)

@bp.route('/signin/', methods=('GET', 'POST'))
def signin():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "It is not your name."
        elif not check_password_hash(user.password, form.password.data):
            error = "It is not your password."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.mainpage'))
        flash(error)
    return render_template('auth/signin.html', form=form)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

@bp.route('/signout/')
def signout():
    session.clear()
    return redirect(url_for('main.mainpage'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.signin'))
        return view(**kwargs)
    return wrapped_view

Di/views/main_views.py
import datetime
import os
import time
import requests
from flask import Blueprint, url_for, render_template, request, send_from_directory, send_file

from werkzeug.utils import redirect, secure_filename


bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/easteregg')
def god_saehan():
    return 'SaeHan is God of Python'

@bp.route('/')
def redirect_first():
    return redirect(url_for('main.mainpage'))

@bp.route('/main')
def mainpage():
    return render_template('main/main.html')

@bp.route('/altar_upload')
def altar():
    return render_template('altar/altar_upload.html')

@bp.route('/fail')
def fail():
    return render_template('altar/fail.html')

filenames = []

@bp.route('/altar_viewer/<now>/<count>')
def viewer(now, count):
    filenames = []
    count = int(count)
    for n in range(1, 100000):
        filenames.append("http://192.168.25.44:5000/static/%s/output_images/%05d.jpg" % (now, n))
    return render_template('altar/altar_viewer.html', filenames=filenames, count=count)

@bp.route('/filename/<now>', methods=['post'])
def filename(now):
    print(now)
    return '%s' % now


@bp.route('/fileupload', methods=['POST'])
def file_upload():
    files = request.files.getlist("file")
    now = datetime.datetime.now().strftime('%Y-%m-%d_%H%M%S')
    os.makedirs('C:/files/%s/videos/' % now, exist_ok=True)
    requests.post('http://192.168.25.250:5000/filename/%s' % now, now)
    for file in files:
        file.save(os.path.join('C:/files/%s/videos/' % now, file.filename))
    start = time.time()
    while True:
        end = time.time()
        timer = end - start
        if os.path.isfile('C:/files/%s/%s.zip' % (now, now)):
            return send_file(os.path.join('C:/files/%s/%s.zip' % (now, now)))
        elif timer > 30:
            return redirect(url_for('main.fail'))
    #return redirect(url_for('main.succeed'))





Di/views/question_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect

from .. import db
from ..forms import QuestionForm, AnswerForm
from Di.models import Question
from Di.views.auth_views import login_required

bp = Blueprint('question', __name__, url_prefix='/question')

@bp.route('/list/')
def _list():
    page = request.args.get('page', type=int, default=1)
    question_list = Question.query.order_by(Question.create_date.desc())
    question_list = question_list.paginate(page, per_page=15)
    return render_template('question/question_list.html', question_list=question_list)

@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html', question=question, form=form)

@bp.route('/write/', methods=('GET', 'POST'))
@login_required
def write():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        question = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now(), user=g.user)
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('question._list'))
    return render_template('question/question_form.html', form=form)

@bp.route('/modify/<int:question_id>', methods=('GET', 'POST'))
@login_required
def modify(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash("You don't have permission")
        return redirect(url_for('question.detail', question_id=question_id))
    if request.method == 'POST':  # POST 요청
        form = QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question)
            question.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))
    else:  # GET 요청
        form = QuestionForm(obj=question)
    return render_template('question/question_form.html', form=form)

@bp.route('/delete/<int:question_id>')
@login_required
def delete(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash("You don't have permission")
        return redirect(url_for('question.detail', question_id=question_id))
    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('question._list'))


Di/templates/question/question_detail.html
<title>Legends of AI</title>
<link rel="icon" href="{{ url_for('static', filename='images/icon.png') }}"/>
<script src="{{ url_for('static', filename='jquery-3.6.0.js') }}"></script>
<style>
            @import url(https://fonts.googleapis.com/css?family=Open+Sans);

html {
  height:100%;
  background-image: linear-gradient(to right top, #8e44ad 0%, #3498db 100%);
}

nav {
  max-width: 960px;
  mask-image: linear-gradient(90deg, rgba(255, 255, 255, 0) 0%, #ffffff 25%, #ffffff 75%, rgba(255, 255, 255, 0) 100%);
  margin: 0 auto;
  padding: 40px 0;
}

nav ul {
  text-align: center;
  background: linear-gradient(90deg, rgba(255, 255, 255, 0) 0%, rgba(255, 255, 255, 0.2) 25%, rgba(255, 255, 255, 0.2) 75%, rgba(255, 255, 255, 0) 100%);
  box-shadow: 0 0 25px rgba(0, 0, 0, 0.1), inset 0 0 0px rgba(255, 255, 255, 0.6);
}

nav ul li {
  display: inline-block;
}

nav ul li a {
  padding: 18px;
  font-family: "Open Sans";
  text-transform:uppercase;
  color: rgba(0, 0, 0, 1);
  font-size: 18px;
  text-decoration: none;
  display: block;
}

nav ul li a:hover {
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1), inset 0 0 1px rgba(255, 255, 255, 0.6);
  background: rgba(255, 255, 255, 0.1);
  color: rgba(0, 0, 0, 0.7);
}

</style>
<body class="bg-secondary">
<div style="text-align : center;"><a href="{{ url_for('main.mainpage') }}"><img src="{{ url_for('static', filename='images/logo.png') }}"/></a></div>
    <nav>
        <ul>
            <li>
                <a href="{{ url_for('main.mainpage') }}">Home</a>
            </li>
            <li>
                <a href="{{ url_for('main.altar') }}">Altar</a>
            </li>
            <li>
                <a href="{{ url_for('question._list') }}">Library</a>
            </li>
            {% if g.user %}
                <li>
                    <a href="{{ url_for('auth.signout') }}">Sign out</a>
                </li>
                <li>
                    <div style="color: #232323">Hi, {{ g.user.username }}</div>
                </li>
            {% else %}
                <li>
                    <a href="{{ url_for('auth.signin') }}">Sign in</a>
                </li>
                <li>
                    <a href="{{ url_for('auth.signup') }}">Sign up</a>
                </li>
          {% endif %}
        </ul>
    </nav>
<div style="text-align : center;"><a href="{{ url_for('question._list') }}"><img src="{{ url_for('static', filename='images/library_logo.jpg') }}" width="1000" height="485"/></a></div>
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2 text-white">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                <div class="badge badge-light p-2 text-left mx-3">
                    <div class="mb-2">Last modified at</div>
                    <div>{{ question.modify_date|datetime }}</div>
                </div>
                {% endif %}
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">written by {{ question.user.username }} at</div>
                    <div>{{ question.create_date|datetime }}</div>
                </div>
            </div>
            {% if g.user == question.user %}
                <div class="my-3">
                    <a href="{{ url_for('question.modify', question_id=question.id) }}"
                        class="btn btn-sm btn-outline-secondary">Edit</a>
                    <a href="#" class="delete btn btn-sm btn-outline-secondary"
                        data-uri="{{ url_for('question.delete', question_id=question.id) }}">Delete</a>
                </div>
            {% endif %}
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2 text-white">{{ question.answer_set|length }}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge badge-light p-2 text-left mx-3">
                    <div class="mb-2">Last modified at</div>
                    <div>{{ answer.modify_date|datetime }}</div>
                </div>
                {% endif %}
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">written by {{ answer.user.username }} at</div>
                    <div>{{ answer.create_date|datetime }}</div>
                </div>
            </div>
            {% if g.user == answer.user %}
                <div class="my-3">
                    <a href="{{ url_for('answer.modify', answer_id=answer.id) }}"
                        class="btn btn-sm btn-outline-secondary">Edit</a>
                    <a href="#" class="delete btn btn-sm btn-outline-secondary "
                data-uri="{{ url_for('answer.delete', answer_id=answer.id) }}">Delete</a>
                </div>
            {% endif %}
        </div>
    </div>
    {% endfor %}
    <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post" class="my-3">
        {{ form.csrf_token }}
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}
        <div class="form-group">
            <textarea {% if not g.user %}disabled{% endif %}
                    name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("You want delete this?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}
</body>

Di/templates/question/question_form.html
<title>Legends of AI</title>
<link rel="icon" href="{{ url_for('static', filename='images/icon.png') }}"/>
{% extends 'base.html' %}
{% block content %}
<style>
            @import url(https://fonts.googleapis.com/css?family=Open+Sans);

nav {
  max-width: 960px;
  mask-image: linear-gradient(90deg, rgba(255, 255, 255, 0) 0%, #ffffff 25%, #ffffff 75%, rgba(255, 255, 255, 0) 100%);
  margin: 0 auto;
  padding: 40px 0;
}

nav ul {
  text-align: center;
  background: linear-gradient(90deg, rgba(255, 255, 255, 0) 0%, rgba(255, 255, 255, 0.2) 25%, rgba(255, 255, 255, 0.2) 75%, rgba(255, 255, 255, 0) 100%);
  box-shadow: 0 0 25px rgba(0, 0, 0, 0.1), inset 0 0 0px rgba(255, 255, 255, 0.6);
}

nav ul li {
  display: inline-block;
}

nav ul li a {
  padding: 18px;
  font-family: "Open Sans";
  text-transform:uppercase;
  color: rgba(0, 0, 0, 1);
  font-size: 18px;
  text-decoration: none;
  display: block;
}

nav ul li a:hover {
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1), inset 0 0 1px rgba(255, 255, 255, 0.6);
  background: rgba(255, 255, 255, 0.1);
  color: rgba(0, 0, 0, 0.7);
}


</style>
<body style="background: #050505">
<div style="text-align: center"><a href="{{ url_for('main.mainpage') }}"><img src="{{ url_for('static', filename='images/logo.png') }}"/></a></div>
    <nav>
        <ul>
            <li>
                <a href="{{ url_for('main.mainpage') }}">Home</a>
            </li>
            <li>
                <a href="{{ url_for('main.altar') }}">Altar</a>
            </li>
            <li>
                <a href="{{ url_for('question._list') }}">Library</a>
            </li>
            {% if g.user %}
                <li>
                    <a href="{{ url_for('auth.signout') }}">Sign out</a>
                </li>
                <li>
                    <div style="color: #232323">Hi, {{ g.user.username }}</div>
                </li>
            {% else %}
                <li>
                    <a href="{{ url_for('auth.signin') }}">Sign in</a>
                </li>
                <li>
                    <a href="{{ url_for('auth.signup') }}">Sign up</a>
                </li>
          {% endif %}
        </ul>
    </nav>
<div style="text-align : center;"><a href="{{ url_for('question._list') }}"><img src="{{ url_for('static', filename='images/library_logo.jpg') }}" width="1000" height="485"/></a></div>
<div class="container" style="color: white">
    <h5 class="my-3 border-bottom pb-2">Post you think about</h5>
    <form method="post" class="post-form my-3">
        {{ form.csrf_token }}
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}
    <div class="form-group">
                <label for="subject">Title</label>
                <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.data or '' }}">
            </div>
            <div class="form-group">
                <label for="content">Description</label>
                <textarea class="form-control" name="content" id="content" rows="8">{{ form.content.data or '' }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">Post</button>
    </form>
</div>
</body>
{% endblock %}

Di/templates/question/question_list.html
<head>
    <title>Legends of AI</title>
    <link rel="icon" href="{{ url_for('static', filename='images/icon.png') }}"/>
    <style>
                @import url(https://fonts.googleapis.com/css?family=Open+Sans);

html {
  height:100%;
  background-image: linear-gradient(to right top, #8e44ad 0%, #3498db 100%);
}

nav {
  max-width: 960px;
  mask-image: linear-gradient(90deg, rgba(255, 255, 255, 0) 0%, #ffffff 25%, #ffffff 75%, rgba(255, 255, 255, 0) 100%);
  margin: 0 auto;
  padding: 40px 0;
}

nav ul {
  text-align: center;
  background: linear-gradient(90deg, rgba(255, 255, 255, 0) 0%, rgba(255, 255, 255, 0.2) 25%, rgba(255, 255, 255, 0.2) 75%, rgba(255, 255, 255, 0) 100%);
  box-shadow: 0 0 25px rgba(0, 0, 0, 0.1), inset 0 0 0px rgba(255, 255, 255, 0.6);
}

nav ul li {
  display: inline-block;
}

nav ul li a {
  padding: 18px;
  font-family: "Open Sans";
  text-transform:uppercase;
  color: rgba(0, 0, 0, 1);
  font-size: 18px;
  text-decoration: none;
  display: block;
}

nav ul li a:hover {
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1), inset 0 0 1px rgba(255, 255, 255, 0.6);
  background: rgba(255, 255, 255, 0.1);
  color: rgba(0, 0, 0, 0.7);
}


    </style>
</head>
<body class="bg-secondary">
<div style="text-align : center;"><a href="{{ url_for('main.mainpage') }}"><img src="{{ url_for('static', filename='images/logo.png') }}"/></a></div>
<nav>
        <ul>
            <li>
                <a href="{{ url_for('main.mainpage') }}">Home</a>
            </li>
            <li>
                <a href="{{ url_for('main.altar') }}">Altar</a>
            </li>
            <li>
                <a href="{{ url_for('question._list') }}">Library</a>
            </li>
            {% if g.user %}
                <li>
                    <a href="{{ url_for('auth.signout') }}">Sign out</a>
                </li>
                <li>
                    <div style="color: #232323">Hi, {{ g.user.username }}</div>
                </li>
            {% else %}
                <li>
                    <a href="{{ url_for('auth.signin') }}">Sign in</a>
                </li>
                <li>
                    <a href="{{ url_for('auth.signup') }}">Sign up</a>
                </li>
          {% endif %}
        </ul>
</nav>
<div style="text-align : center;"><a href="{{ url_for('question._list') }}"><img src="{{ url_for('static', filename='images/library_logo.jpg') }}" width="1000" height="485"/></a></div>

{% extends 'base.html' %}
{% block content %}
<div class="container my-3" id="list">
    <table class="table">
        <thead>
        <tr class="thread-dark">
            <th class="text-white">No.</th>
            <th class="text-white">Title</th>
            <th class="text-white">Writer</th>
            <th class="text-white">Date</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list.items %}
        <tr>
            <td class="text-white">{{ question.id }}</td>
            <td>
                <a class="text-white" href="{{ url_for('question.detail', question_id=question.id) }}">{{ question.subject }}</a>
                {% if question.answer_set|length > 0 %}
                <span class="text-danger small ml-2">{{ question.answer_set|length }}</span>
                {% endif %}
            </td>
            <td class="text-white">{{ question.user.username }}</td>
            <td class="text-white">{{ question.create_date|datetime }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{{ url_for('question.write') }}" class="btn btn-primary">Post</a>
    <ul class="pagination justify-content-center">
        <!-- prev page -->
        {% if question_list.has_prev %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.prev_num }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        {% for page_num in question_list.iter_pages() %}
            {% if page_num %}
                {% if page_num != question_list.page %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{ page_num }}</a>
                </li>
                {% endif %}
           {% else %}
                <li class="disabled">
                    <a class="page-link" href="#">...</a>
                </li>
           {% endif %}
        {% endfor %}
            <!-- next page -->
            {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link btn btn-success" href="?page={{ question_list.next_num }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link btn btn-success" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
</div>
{% endblock %}
</body>